proofit404/dependencies

- azure-pipelines.yml
- codecov.yml
> Setup Codecov README and documentation badges.

- src/dependencies/_checks/func.py
- tests/test_injector.py
> Clarify `argument can not have class as its default value` error

- src/dependencies/_injector.py
This is mostly a style fix but it is slightly faster to build a dictionary this way as well.
> Use a dict comprehension

- azure-pipelines.yml
- release.config.js
- tox.ini
Apply pre-commit hooks (i.e. prettier) to the generated changelog before committing it to the codebase.
> Prevent generated changelog from style guide violation.

- .readthedocs.txt
- .readthedocs.yml
- pyproject.toml
- release.config.js
- tests/test_configuration.py
- tox.ini
> Move mkdocs out of pyproject.toml.

- .coveragerc
- src/_dependencies/injector.py
- tests/helpers/doctested_module.py
- tests/helpers/mddoctest.py
- tests/helpers/pyproject.toml
> doctest support  

- src/_dependencies/checks/injector.py
- src/_dependencies/checks/loops.py
- src/_dependencies/checks/this.py
- src/_dependencies/contrib/pytest.py
- src/_dependencies/contrib/rest_framework.py
- src/_dependencies/injector.py
- src/_dependencies/operation.py
- src/_dependencies/package.py
- src/_dependencies/spec.py
- src/_dependencies/value.py
- tests/helpers/django_project/api/urls.py
- tests/test_checks_loops.py
- tests/test_contrib_django.py
- tests/test_contrib_rest_framework_generic_view_set.py
- tests/test_contrib_rest_framework_view_set.py
- tests/test_package.py
- tests/test_this.py
- tox.ini
> Setup flake8 FIXME plugin.

- azure-pipelines.yml
- dangerfile.ts
- package.json
> Adapt danger tool.

- tests/test_configuration.py
> Ensure multiline tox settings are written on the new line.

- azure-pipelines.yml
- dangerfile.ts
> Improve dangerfile.

- .github/FUNDING.yml
- .readthedocs.txt
- .readthedocs.yml
- LICENSE
- README.md
- azure-pipelines.yml
- dangerfile.ts
- docs/attrs.md
- docs/changelog.md
- docs/faq.md
- docs/implementation.md
- docs/index.md
- docs/overview.md
- docs/proxies/operation.md
- docs/proxies/package.md
- docs/proxies/this.md
- docs/usage.md
- docs/why.md
- mkdocs.yml
- pyproject.toml
- release.config.js
- src/dependencies/__init__.py
- src/dependencies/exceptions.py
- tests/helpers/mddoctest.py
- tests/test_configuration.py
> Migrate repository.

- README.md
- azure-pipelines.yml
- pyproject.toml
> Deploy documentation to the GitHub pages.

- .pre-commit-config.yaml
- .prettierignore
- release.config.js
- tests/test_configuration.py
- tox.ini
> Migrate from pre-commit to tox.

- docs/index.md
> Asking questions on the task tracker.

- .gitignore
- tox.ini
> Isolate npm installation in different directories.

- .flake8
- .yamllint
- tests/test_configuration.py
> Ignore obsolete node_modules directory.

- dangerfile.ts
> Improve dangerfile rules.

- azure-pipelines.yml
- docs/attrs.md
- docs/changelog.md
- docs/faq.md
- docs/implementation.md
- docs/index.md
- docs/overview.md
- docs/proxies/operation.md
- docs/proxies/package.md
- docs/proxies/this.md
- docs/usage.md
- docs/why.md
- tox.ini
> Enable prose wrap prettier option.

- src/_dependencies/injector.py
- tests/test_typing.py
> Compatibility with typing module on Python 3.6.

- docs/faq.md
- docs/this.md
- docs/usage.md
- docs/why.md
- tox.ini
- vale.install.sh
> Setup vale tool.

- docs/why.md
> Correct prose lint violations.

- docs/index.md
> Introduce enterprise support.

- docs/installation.md
- mkdocs.yml
> Correct code blocks.

- dangerfile.ts
> Validate repository label colors.

- docs/sticky.md
- mkdocs.yml
- src/_dependencies/injector.py
- tests/helpers/app/services.py
- tests/helpers/app/transactions.py
- tests/test_scope.py
> Implement sticky scopes.

- src/_dependencies/injector.py
- src/_dependencies/objects/nested.py
- src/_dependencies/resolve.py
- src/_dependencies/scope.py
- src/_dependencies/state.py
- tests/test_injector.py
- tests/test_objects_this.py
> Show resolver stack in missing dependency hint.

- docs/nested.md
- src/_dependencies/graph.py
- src/_dependencies/objects/classes.py
- src/_dependencies/objects/nested.py
- src/_dependencies/resolve.py
- src/_dependencies/state.py
- tests/test_objects_nested.py
- tests/test_objects_this.py
> Show proper hint on nested injector missed dependency.

- src/_dependencies/resolve.py
- src/_dependencies/trace.py
- tests/test_injector.py
> Show correct error message for circle error.

- src/_dependencies/trace.py
- tests/test_injector.py
> Correct stack representation in circle error message.

- src/_dependencies/objects/package.py
- src/_dependencies/objects/this.py
- src/_dependencies/resolve.py
- tests/helpers/examples/__init__.py
- tests/helpers/examples/import_error.py
- tests/test_objects_package.py
> Correct possible recursion error caused by package import.

- src/_dependencies/objects/package.py
- tests/test_objects_package.py
> Deny relative imports in Package declaration.

- LICENSE
- src/_dependencies/objects/this.py
- tests/helpers/configuration.py
- tests/test_objects_this.py
> This object should not trigger unwrap error.

- .coveragerc
- docs/sticky.md
- src/_dependencies/delegate.py
- src/_dependencies/injector.py
- testing/attributes.py
- tests/conftest.py
- tests/test_injector.py
- tests/test_objects_data.py
- tests/test_objects_nested.py
- tests/test_objects_package.py
- tests/test_objects_this.py
- tests/test_objects_value.py
> Restrict sticky scopes.

- docs/value.md
- tests/test_objects_value.py
> @value object should support decorated functions.

- docs/setup_teardown.md
- mkdocs.yml
- src/_dependencies/enclose.py
- src/_dependencies/graph.py
- src/_dependencies/injector.py
- src/_dependencies/objects/attributes.py
- src/_dependencies/objects/classes.py
- src/_dependencies/objects/data.py
- src/_dependencies/objects/nested.py
- src/_dependencies/objects/this.py
- src/_dependencies/objects/value.py
- src/_dependencies/resolve.py
- src/_dependencies/scope.py
- src/_dependencies/spec.py
- src/_dependencies/stack.py
- testing/app/models.py
- testing/mddoctest.py
- tests/test_setup_and_teardown.py
> Setup and teardown for @value objects.

- docs/setup_teardown.md
- src/_dependencies/enclose.py
- testing/app/database.py
- tests/test_setup_and_teardown.py
> Setup and teardown steps execution order.

- docs/classes.md
- mkdocs.yml
- src/_dependencies/injectable.py
- testing/examples/positional_only.py
- tests/test_injectable.py
> Support positional-only arguments.

- docs/shield.md
- mkdocs.yml
- src/_dependencies/analyze.py
- src/_dependencies/objects/shield.py
- src/dependencies/__init__.py
- tests/test_objects_shield.py
> Pass positional arguments to shield object.

- .coveragerc
- docs/shield.md
- testing/examples1/__init__.py
- testing/examples1/definitions.py
- tests/conftest.py
- tests/test_objects_shield.py
> Pass this object as shield arguments.

- docs/shield.md
- testing/examples/__init__.py
- tests/test_objects_shield.py
> Explain package object as shield argument.

- .coveragerc
- docs/config.yml
- docs/settings.md
- mkdocs.yml
- testing/application.py
- testing/consul.py
- testing/mddoctest.py
- tox.ini
> Explain project settings.

- .coveragerc
- docs/direct_resolve.md
- docs/package.md
- docs/shield.md
- pyproject.toml
- pytest.ini
- src/_.py
- src/_dependencies/objects/package.py
- src/_dependencies/objects/this.py
- testing/examples/self_pointer.py
- tests/test_direct_resolve.py
- tests/test_injectable.py
- tests/test_objects_descriptor.py
- tests/test_objects_package.py
- tests/test_objects_shield.py
> Deprecate `this` and `Package` objects.
